export const actions = {
    FETCHING_DEST_DATA : 'FETCHING_DEST_DATA',
    FETCHED_DEST_DATA : 'FETCHED_DEST_DATA',
    FETCHING_DEST_DATA_ERROR : 'FETCHING_DEST_DATA_ERROR',
    FETCHING_TOUR_DATA : 'FETCHING_TOUR_DATA',
    FETCHED_TOUR_DATA : 'FETCHED_TOUR_DATA',
    FETCHING_TOUR_DATA_ERROR : 'FETCHING_TOUR_DATA_ERROR',
}

